#' From cie10 to Enos.
#' @param x death code.
#' @param age age.
#' @param age_code age code. Assume code_age levels 1 = years, 2 = months, 3 = days, 4 = hours, 5 = minutes.

code_enos <- function(x, age, age_code){

  dplyr::case_when(
    (x >= 'A000' & x <= 'A09X') ~ '06 - DIARREAS AGUDAS',
    (x >= 'A010' & x <= 'A014') ~ '07 - FIEBRE TIFOIDEA Y PARATIFOIDEA',
    (x >= 'A000' & x <= 'A09X') ~ '10 - ENFERMEDADES DE TRANSIMISION ALIMENTARIA - (ETA)',
    (x >= 'A540' & x <= 'A542') ~ '18 - URETRITIS GONOCOCCICA (GONORREA  BLENORRAGIA)',
    (x >= 'A500' & x <= 'A52X') ~ '19 - SIFILIS DEL ADULTO (o adquirida) Y SIFILIS CONGENITA',
    (x >= 'B200' & x <= 'B24X') ~ '20 - SIDA',
    (x >= 'T360' & x <= 'T50X') ~ '31 - INTOXICACIÓN MEDICAMENTOSA',
    (x >= 'T510' & x <= 'T65X') ~ '34 - OTROS TÓXICOS',
    (x >= 'V010' & x <= 'V99X') ~ '35 - ACCIDENTES DE TRANSPORTE',
    (x >= 'W000' & x <= 'X59X') ~ '36 - OTRAS CAUSAS EXTERNAS DE TRAUMATISMOS ACCIDENTALES',
    (x >= 'X600' & x <= 'X84X') ~ '37 - LESIONES AUTOINFLINGIDAS INTENCIONALMENTE',
    (x >= 'Y100' & x <= 'Y34X') ~ '38 - EVENTOS DE INTENCIÓN NO DETERMINADA',
    (x >= 'Y400' & x <= 'Y84X') ~ '39 - COMPLICACIONES DE LA ATENCIÓN MÉDICA Y QUIRÚRGICA',
    (x >= 'W000' & x <= 'Y34X') & !str_detect(x, 'Y06|Y07') ~ '40 - ACCIDENTES EN EL HOGAR',
    (x >= 'A150' & x <= 'A19X') & ((age <= 4 & age_code == 1) | (age_code %in% 2:5)) ~ '45 - MENINGOENCEFALITIS TUBERCULOSA EN MENORES DE 5 AÑOS',
    (x >= 'J090' & x <= 'J11X') ~ '46 - INFLUENZA',
    (x >= 'J120' & x <= 'J18X') ~ '47 - NEUMONIA',
    (x >= 'A150' & x <= 'A19X') ~ '50 - TUBERCULOSIS',
    (x >= 'B500' & x <= 'B54X') ~ '59 - PALUDISMO (MALARIA)',
    stringr::str_detect(x, 'A30') ~ '01 - LEPRA',
    stringr::str_detect(x, 'T630') ~ '02 - OFIDISMO',
    stringr::str_detect(x, 'T633') ~ '03 - ARACNIDISMO',
    stringr::str_detect(x, 'T632') ~ '04 - ESCORPIONISMO',
    stringr::str_detect(x, 'A059') ~ '05 - INTOXICACION PARALÍTICA POR MOLUSCOS (IPM)',
    stringr::str_detect(x, 'A043') ~ '08 - SINDROME UREMICO HEMOLITICO (SUH)',
    stringr::str_detect(x, 'A00') ~ '09 - COLERA',
    stringr::str_detect(x, 'B75') ~ '11 - TRIQUINOSIS',
    stringr::str_detect(x, 'A051') ~ '12 - BOTULISMO',
    stringr::str_detect(x, 'B15') ~ '13 - HEPATITIS VIRAL TIPO A',
    stringr::str_detect(x, 'B16') ~ '14 - HEPATITIS VIRAL TIPO B',
    stringr::str_detect(x, 'B171') ~ '15 - HEPATITIS VIRAL TIPO C',
    stringr::str_detect(x, 'B170') ~ '16 - HEPATITIS VIRAL TIPO D',
    stringr::str_detect(x, 'B172') ~ '17 - HEPATITIS VIRAL TIPO E',
    stringr::str_detect(x, 'B01') ~ '21 - VARICELA',
    stringr::str_detect(x, 'B26') ~ '22 - PAROTIDITIS INFECCIOSA (Paperas)',
    stringr::str_detect(x, 'A80') ~ '23 - POLIOMIELITIS CIE10',
    stringr::str_detect(x, 'A37') ~ '24 - COQUELUCHE (Tos Convulsa)',
    stringr::str_detect(x, 'A35') ~ '25 - TÉTANOS OTRAS EDADES',
    stringr::str_detect(x, 'A33') ~ '26 - TETANOS NEONATAL',
    stringr::str_detect(x, 'A36') ~ '27 - DIFTERIA CIE10',
    stringr::str_detect(x, 'P350') ~ '28 - SINDROME DE RUBEOLA CONGENITA (SRC)',
    stringr::str_detect(x, 'B05') ~ '29 - SARAMPION',
    stringr::str_detect(x, 'B06') ~ '30 - RUBEOLA',
    stringr::str_detect(x, 'T58') ~ '32 - INTOXICACIÓN POR MONÓXIDO DE CARBONO',
    stringr::str_detect(x, 'T60') ~ '33 - INTOXICACIÓN POR PLAGUICIDAS',
    stringr::str_detect(x, 'A87') ~ '41 - MENINGITIS NO PIOGENA',
    stringr::str_detect(x, 'A390') ~ '42 - MENINGITIS MENINGOCOCCICA',
    stringr::str_detect(x, 'G000') ~ '43 - MENINGITIS POR HAEMOPHILUS',
    stringr::str_detect(x, 'G001') ~ '44 - MENINGITIS NEUMOCÓCCICA',
    stringr::str_detect(x, 'J21') & ((age <= 2 & age_code == 1) | (age_code %in% 2:5)) ~ '48 - BRONQUIOLITIS',
    stringr::str_detect(x, 'U049') ~ '49 - SINDROME RESPIRATORIO AGUDO SEVERO',
    stringr::str_detect(x, 'B550') ~ '51 - LEISHMANIASIS VISCERAL',
    stringr::str_detect(x, 'B552') ~ '52 - LEISHMANIASIS MUCOSA (O MUCOCUTANEA)',
    stringr::str_detect(x, 'B551') ~ '53 - LEISHMANIASIS CUTANEA',
    stringr::str_detect(x, 'A950') ~ '54 - FIEBRE AMARILLA SELVÁTICA',
    stringr::str_detect(x, 'A951') ~ '55 - FIEBRE AMARILLA URBANA',
    stringr::str_detect(x, 'A852') ~ '56 - ENCEFALITIS POR ARBOVIRUS',
    stringr::str_detect(x, 'A90') ~ '57 - DENGUE',
    stringr::str_detect(x, 'A91') ~ '58 - DENGUE HEMORRAGICO/ SINDROME DE CHOQUE DEL DENGUE (DH/SCD)',
    stringr::str_detect(x, 'B57') ~ '60 - ENFERMEDAD DE CHAGAS (AGUDO Y CONGÉNITO)',
    stringr::str_detect(x, 'A750') ~ '61 - TIFUS EPIDEMICO',
    stringr::str_detect(x, 'A20') ~ '62 - PESTE',
    stringr::str_detect(x, 'A923') ~ '63 - FIEBRE DEL NILO OCCIDENTAL',
    stringr::str_detect(x, 'A82') ~ '64 - RABIA HUMANA',
    stringr::str_detect(x, 'A70') ~ '65 - PSITACOSIS',
    stringr::str_detect(x, 'A22') ~ '66 - CARBUNCO',
    stringr::str_detect(x, 'B670') ~ '67 - HIDATIDOSIS',
    stringr::str_detect(x, 'A23') ~ '68 - BRUCELOSIS',
    stringr::str_detect(x, 'B334') ~ '69 - HANTAVIRUS - SINDROME PULMONAR',
    stringr::str_detect(x, 'A27') ~ '70 - LEPTOSPIROSIS',
    stringr::str_detect(x, 'A960') ~ '71 - FIEBRE HEMORRÁGICA',
    T ~ 'Not ENOs')
}
